name: mad_legend
description: Mad Legend

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  flame: ^0.18.0
  shared_preferences: 0.5.6+1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  fonts:
    - family: Malloy
      fonts:
        - asset: assets/fonts/17607.otf

    - family: YagiDouble
      fonts:
        - asset: assets/fonts/17849.ttf

  uses-material-design: true

  assets:
    - assets/images/knight.png
    - assets/images/archer.png
    - assets/images/trees_close_900.png
    - assets/images/moon_765.png
    - assets/images/tree_30_663.png
    - assets/images/tree_663.png
    - assets/images/trees_30_891.png
    - assets/images/white_gradient.png
    - assets/images/trees_50_471.png
    - assets/images/game_bg_trees.png
    - assets/images/arrow_default.png
    - assets/images/sword_default.png
    - assets/images/shield_default.png
    - assets/images/curse_default.png
    - assets/images/improvement_default.png
    - assets/images/prepare_default.png
    - assets/images/card_shadow.png
    - assets/images/garbage_default.png